### ISSUE TITLE
Fields are not showing in the manager if allowBlank is set to false 

### ISSUE THREAD

**Issue by kinaz** [Jako/DaterangeTV#9]
Hi,

after upgrading yo 1.3.1-pl3, my daterange TVs don't show anymore.

After some debugging I found that the daterange fields don't show if allowBlank is set to NO. They do if it's set to YES.

Here is what I found in the manager html source of a resource with a daterange tv:

**allowBlank set to false:**
...

```
<script type="text/javascript">
    // <![CDATA[
    Ext.onReady(function () {
        MODx.load({
            xtype: 'daterangetv-combo-daterangetv',
            tvId: '17',
            daterangeFormat: '' || MODx.config['manager_date_format'],
            allowBlank: ,
            daterangeStart: '',
            daterangeEnd: '',
            endTV: '',
            renderTo: 'modx-daterange-tv17'
        });
    });
    // ]]>
</script>
```
...

**allowBlank set to true:**
...

```
<script type="text/javascript">
    // <![CDATA[
    Ext.onReady(function () {
        MODx.load({
            xtype: 'daterangetv-combo-daterangetv',
            tvId: '17',
            daterangeFormat: '' || MODx.config['manager_date_format'],
            allowBlank: 1,
            daterangeStart: '',
            daterangeEnd: '',
            endTV: '',
            renderTo: 'modx-daterange-tv17'
        });
    });
    // ]]>
</script>
```
...

**Comment by Jako** [comment]
I have fixed a similar issue in Image+ lately. The fix should be similar to this: https://github.com/Jako/ImagePlus/commit/1dfb248a453edcbd8568f6a03fa29c66f349db4a#diff-752c693f25b6b331c07e43ba8f0352a5R73

Could you try to test this fix on daterangeTV?

**Comment by Jako** [comment]
Fixed with 1.3.2

**Comment by kinaz** [comment]
Thanks!

**Comment by kinaz** [comment]
Hi @Jako,

looks like the bug is back on 1.3.3:

https://github.com/Jako/DaterangeTV/blob/a138169f96edfc4d3c0f3024b12350287d4a67c7/core/components/daterangetv/elements/tv/input/daterange.class.php#L77

This modification seems to make it working again:

$params['allowBlank'] = ($params['allowBlank'] == 'false' || $params['allowBlank'] == 0 || $params['allowBlank'] == false) ? 'false' : 'true';

**Comment by Jako** [comment]
This should be finally fixed with 1.3.4
